//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmuGrossMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class irsaliye
    {
        public int irsaliyeNo { get; set; }
        public int urunGirdiMiktari { get; set; }
        public int urunFiyati { get; set; }
        public int tedarikciID { get; set; }
        public int urunID { get; set; }
        public int barkodNo { get; set; }
    
        public virtual tedarikci tedarikci { get; set; }
        public virtual urun urun { get; set; }
    }
}
