//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmuGrossMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class omuGrossDataBaseEntities1 : DbContext
    {
        public omuGrossDataBaseEntities1()
            : base("name=omuGrossDataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<irsaliye> irsaliye { get; set; }
        public virtual DbSet<market> market { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<musteriOdeme> musteriOdeme { get; set; }
        public virtual DbSet<perakendeSatis> perakendeSatis { get; set; }
        public virtual DbSet<tedarikci> tedarikci { get; set; }
        public virtual DbSet<urun> urun { get; set; }
        public virtual DbSet<urunStokDurum> urunStokDurum { get; set; }
        public virtual DbSet<musteriBorc> musteriBorc { get; set; }
        public virtual DbSet<pesinSatis> pesinSatis { get; set; }
        public virtual DbSet<tedarikciBorc> tedarikciBorc { get; set; }
        public virtual DbSet<tedarikciOdeme> tedarikciOdeme { get; set; }
        public virtual DbSet<veresiye> veresiye { get; set; }
    }
}
