
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OmuGrossMarket
{

using System;
    using System.Collections.Generic;
    
public partial class musteriOdeme
{

    public int id { get; set; }

    public int odemeMiktari { get; set; }

    public System.DateTime odemeTarihi { get; set; }

    public int musteriID { get; set; }



    public virtual musteri musteri { get; set; }

}

}
